# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: WebUI Testcases Execution 🚀

on:
  schedule:
    # Runs everyday 13:00 UTC
    - cron: '00 13 * * *'
  workflow_dispatch:
  pull_request:

jobs:
  Test WebUI:
    name: Run tests and generate the allure report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pipenv wheel
          pipenv install
      - name: Run the testcases
        run: pytest

